### ISSUE TITLE
Mario Party Series Rendering Issues (Could Be RSP As Well?)

### ISSUE THREAD

**Issue by wildgoosespeeder** [project64/angrylion-rdp#1]
- Windows 8.1 Pro 64-bit
- 12GB RAM
- Intel Core i5-3210M@2.5Ghz

- Project64 v2.2
--angrylion (June 2015)
--HatCat RSP

These issues seem to be a problem with the Mario Party games, mostly with Mario Party 2 minigames. I verified them with GoodTools and they are good dumps ((U) [!]). These are just some parts of the games not working right. It's not limited to these.

**Mario Party:**
Mushroom Mix-up:
![mushroom mix-up](https://cloud.githubusercontent.com/assets/18543809/23336367/dad6bbc0-fb93-11e6-89cf-478838851e15.png)
Skateboard Scamper:
![skateboard scamper](https://cloud.githubusercontent.com/assets/18543809/23336368/dadaa30c-fb93-11e6-8e68-47da9be49043.png)

**Mario Party 2:**
General play:
![garbage text](https://cloud.githubusercontent.com/assets/18543809/23336364/dad38f9a-fb93-11e6-8668-6c6aa6758efa.png)
Lava Tile Isle:
![lava tile isle](https://cloud.githubusercontent.com/assets/18543809/23336365/dad4d6ac-fb93-11e6-9a2c-ceff534e3aa2.png)
Hexagon Heat:
![hexagon heat](https://cloud.githubusercontent.com/assets/18543809/23336366/dad589bc-fb93-11e6-85bd-d113f2214d8b.png)

**Comment by project64** [comment]
have you tried pj64 rsp interpter and pj64 main cpu interpter?

**Comment by wildgoosespeeder** [comment]
It's HatCat's RSP. Thanks. Using *RSP 1.7.dll* fixes the issue except for:
![garbage text](https://cloud.githubusercontent.com/assets/18543809/23336364/dad38f9a-fb93-11e6-8668-6c6aa6758efa.png)
